/**
 * 3-way Python↔TypeScript↔Rust differential fuzzer for music_dsl.
 *
 * Reads:
 *   conformance/music-dsl/fuzz/inputs.json      — generated by gen.py
 *   conformance/music-dsl/fuzz/python_out.json  — oracle produced by oracle.py
 *   conformance/music-dsl/fuzz/rust_out.json    — produced by `cargo run --bin fuzz_runner`
 *
 * For each record:
 *   - Runs the same op through the TS port.
 *   - Asserts TS == Python (oracle).
 *   - Asserts Rust == Python (oracle).
 *   Both-error → PASS. One-error-one-ok → FAIL. Divergent models → FAIL.
 *
 * Run via the music-dsl/ts vitest config:
 *   cd music-dsl/ts
 *   NODE_PATH=node_modules node node_modules/.bin/vitest run \
 *     --config ../../conformance/music-dsl/fuzz/vitest.fuzz.config.ts
 */
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import {
  parseChord,
  serializeChord,
  fromChordString,
  fromChord,
  serializeNumericChord,
  noteToMidi,
  chordPitches,
  scalePitches,
  scaleDegreePitch,
  modulate,
  isDiatonic,
  chordInKey,
} from "music_dsl";

const HERE = dirname(fileURLToPath(import.meta.url));

type FuzzInput =
  | { kind: "chord"; input: string }
  | { kind: "numeric"; input: string }
  | { kind: "numeric_from_chord"; key_root: string; chord: string; substitution: boolean }
  | { kind: "chord_pitches"; chord: string; octave: number }
  | { kind: "scale_pitches"; root: string; scale: string; octave: number }
  | { kind: "scale_degree_pitch"; degree: string; key_root: string; octave: number }
  | { kind: "note_to_midi"; note: string; octave: number }
  | { kind: "modulate"; semitones: number; note: string }
  | { kind: "is_diatonic"; root: string; scale: string; chord: string }
  | { kind: "chord_in_key"; numeric: string; key_root: string };

type FuzzOutput =
  | { name: string; kind: string; error: true }
  | { name: string; kind: string; result: Record<string, unknown> };

const inputs: FuzzInput[] = JSON.parse(
  readFileSync(join(HERE, "inputs.json"), "utf-8"),
) as FuzzInput[];

const pythonOutputs: FuzzOutput[] = JSON.parse(
  readFileSync(join(HERE, "python_out.json"), "utf-8"),
) as FuzzOutput[];

const rustOutPath = join(HERE, "rust_out.json");
const rustOutputs: FuzzOutput[] | null = existsSync(rustOutPath)
  ? JSON.parse(readFileSync(rustOutPath, "utf-8")) as FuzzOutput[]
  : null;

// ---------------------------------------------------------------------------
// TS ops — mirrors Python runner's OPS but returns the same shapes as oracle.py
// ---------------------------------------------------------------------------

function tsRunChord(input: string): { result: Record<string, unknown> } | { error: true } {
  try {
    const chord = parseChord(input);
    return { result: { chord: serializeChord(chord) } };
  } catch {
    return { error: true };
  }
}

function tsRunNumeric(input: string): { result: Record<string, unknown> } | { error: true } {
  try {
    const model = fromChordString(input);
    return { result: { numeric: serializeNumericChord(model) } };
  } catch {
    return { error: true };
  }
}

function tsRunNumericFromChord(
  keyRoot: string,
  chordStr: string,
  substitution: boolean,
): { result: Record<string, unknown> } | { error: true } {
  try {
    const chord = parseChord(chordStr);
    const attrs = fromChord(keyRoot, chord, substitution);
    const serialized = serializeNumericChord({ numerator: attrs, denominator: null });
    return { result: { numeric: serialized.numerator } };
  } catch {
    return { error: true };
  }
}

function tsRunChordPitches(
  chordStr: string,
  octave: number,
): { result: Record<string, unknown> } | { error: true } {
  try {
    const chord = parseChord(chordStr);
    const pitches = chordPitches(chord, octave);
    return { result: { pitches } };
  } catch {
    return { error: true };
  }
}

function tsRunScalePitches(
  root: string,
  scale: string,
  octave: number,
): { result: Record<string, unknown> } | { error: true } {
  try {
    const pitches = scalePitches(root, scale, octave);
    return { result: { pitches } };
  } catch {
    return { error: true };
  }
}

function tsRunScaleDegreePitch(
  degree: string,
  keyRoot: string,
  octave: number,
): { result: Record<string, unknown> } | { error: true } {
  try {
    const pitch = scaleDegreePitch(degree, keyRoot, octave);
    return { result: { pitch } };
  } catch {
    return { error: true };
  }
}

function tsRunNoteToMidi(
  note: string,
  octave: number,
): { result: Record<string, unknown> } | { error: true } {
  try {
    const pitch = noteToMidi(note, octave);
    return { result: { pitch } };
  } catch {
    return { error: true };
  }
}

function tsRunModulate(
  semitones: number,
  note: string,
): { result: Record<string, unknown> } | { error: true } {
  try {
    const result = modulate(semitones, note);
    return { result: { note: result } };
  } catch {
    return { error: true };
  }
}

function tsRunIsDiatonic(
  root: string,
  scale: string,
  chordStr: string,
): { result: Record<string, unknown> } | { error: true } {
  try {
    const chord = parseChord(chordStr);
    const diatonic = isDiatonic(root, scale, chord);
    return { result: { diatonic } };
  } catch {
    return { error: true };
  }
}

function tsRunChordInKey(
  numericStr: string,
  keyRoot: string,
): { result: Record<string, unknown> } | { error: true } {
  try {
    const chord = chordInKey(numericStr, keyRoot);
    return { result: { chord } };
  } catch {
    return { error: true };
  }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function isError(out: FuzzOutput | { error: true } | { result: unknown }): boolean {
  return "error" in out && (out as { error: boolean }).error === true;
}

function getResult(out: FuzzOutput | { result: unknown }): unknown {
  return (out as { result: unknown }).result;
}

function describeDivergence(
  label: string,
  testName: string,
  inp: FuzzInput,
  pythonSide: string,
  otherSide: string,
): string {
  return (
    `DIVERGENCE (Python vs ${label}) on ${testName}:\n` +
    `  input:  ${JSON.stringify(inp)}\n` +
    `  python: ${pythonSide}\n` +
    `  ${label.toLowerCase()}:   ${otherSide}`
  );
}

// ---------------------------------------------------------------------------
// 3-way differential test suite
// ---------------------------------------------------------------------------

describe("Python↔TypeScript↔Rust 3-way differential fuzzer (music-dsl)", () => {
  it("input and oracle record counts match", () => {
    expect(inputs.length).toBe(pythonOutputs.length);
  });

  if (rustOutputs) {
    it("rust output count matches input count", () => {
      expect(rustOutputs!.length).toBe(inputs.length);
    });
  }

  for (let i = 0; i < pythonOutputs.length; i++) {
    const oracle = pythonOutputs[i];
    const inp = inputs[i];
    const rustOracle = rustOutputs ? rustOutputs[i] : null;
    const testName = oracle.name;

    it(testName, () => {
      // --- Run TS ---
      let tsOut: { result: Record<string, unknown> } | { error: true };
      if (inp.kind === "chord") {
        tsOut = tsRunChord(inp.input);
      } else if (inp.kind === "numeric") {
        tsOut = tsRunNumeric(inp.input);
      } else if (inp.kind === "numeric_from_chord") {
        tsOut = tsRunNumericFromChord(inp.key_root, inp.chord, inp.substitution);
      } else if (inp.kind === "chord_pitches") {
        tsOut = tsRunChordPitches(inp.chord, inp.octave);
      } else if (inp.kind === "scale_pitches") {
        tsOut = tsRunScalePitches(inp.root, inp.scale, inp.octave);
      } else if (inp.kind === "scale_degree_pitch") {
        tsOut = tsRunScaleDegreePitch(inp.degree, inp.key_root, inp.octave);
      } else if (inp.kind === "note_to_midi") {
        tsOut = tsRunNoteToMidi(inp.note, inp.octave);
      } else if (inp.kind === "modulate") {
        tsOut = tsRunModulate(inp.semitones, inp.note);
      } else if (inp.kind === "is_diatonic") {
        tsOut = tsRunIsDiatonic(inp.root, inp.scale, inp.chord);
      } else if (inp.kind === "chord_in_key") {
        tsOut = tsRunChordInKey(inp.numeric, inp.key_root);
      } else {
        throw new Error(`Unknown kind in input record ${i}: ${JSON.stringify(inp)}`);
      }

      const pythonIsError = isError(oracle);
      const tsIsError = isError(tsOut);

      // --- Python vs TS ---
      if (pythonIsError !== tsIsError) {
        const pythonSide = pythonIsError ? "ERROR" : JSON.stringify(getResult(oracle));
        const tsSide = tsIsError ? "ERROR" : JSON.stringify(getResult(tsOut));
        throw new Error(describeDivergence("TS", testName, inp, pythonSide, tsSide));
      }
      if (!pythonIsError && !tsIsError) {
        expect(
          getResult(tsOut),
          describeDivergence("TS", testName, inp, JSON.stringify(getResult(oracle)), JSON.stringify(getResult(tsOut))),
        ).toEqual(getResult(oracle));
      }

      // --- Python vs Rust (if rust_out.json available) ---
      if (rustOracle !== null) {
        const rustIsError = isError(rustOracle);
        if (pythonIsError !== rustIsError) {
          const pythonSide = pythonIsError ? "ERROR" : JSON.stringify(getResult(oracle));
          const rustSide = rustIsError ? "ERROR" : JSON.stringify(getResult(rustOracle));
          throw new Error(describeDivergence("Rust", testName, inp, pythonSide, rustSide));
        }
        if (!pythonIsError && !rustIsError) {
          expect(
            getResult(rustOracle),
            describeDivergence("Rust", testName, inp, JSON.stringify(getResult(oracle)), JSON.stringify(getResult(rustOracle))),
          ).toEqual(getResult(oracle));
        }
      }
    });
  }
});
