from music_dsl import __version__
from setuptools import find_packages, setup

setup(
    name="music_dsl",
    packages=find_packages(include=["music_dsl"]),
    install_requires=[
        "attrs==21.4.0",
        "beautifulsoup4==4.11.1",
        "black==22.6.0",
        "bs4==0.0.1",
        "click==8.1.3",
        "coverage==6.4.1",
        "cycler==0.11.0",
        "exceptiongroup==1.0.0rc8",
        "fonttools==4.33.3",
        "hypothesis==6.49.1",
        "iniconfig==1.1.1",
        "kiwisolver==1.4.3",
        "matplotlib==3.5.2",
        "mypy==0.982",
        "mypy-extensions==0.4.3",
        "networkx==2.8.4",
        "numpy==1.23.0",
        "packaging==21.3",
        "pathspec==0.9.0",
        "Pillow==9.1.1",
        "platformdirs==2.5.2",
        "pluggy==1.0.0",
        "py==1.11.0",
        "pyparsing==3.0.9",
        "pytest==7.1.2",
        "pytest-cov==3.0.0",
        "python-dateutil==2.8.2",
        "six==1.16.0",
        "sortedcontainers==2.4.0",
        "soupsieve==2.3.2.post1",
        "tomli==2.0.1",
        "typing_extensions==4.2.0",
    ],
    version=__version__,
    description="A library of music domain specific objects.",
    author="Daniel Young",
    license="MIT",
)
