from music_dsl import __version__
from setuptools import find_packages, setup

setup(
    name="music_dsl",
    packages=find_packages(include=["music_dsl"]),
    install_requires=[
        "attrs>=23.0.0",
        "beautifulsoup4>=4.12.0",
        "black>=24.0.0",
        "bs4",
        "click>=8.1.0",
        "coverage>=7.0.0",
        "cycler>=0.12.0",
        "fonttools>=4.50.0",
        "hypothesis>=6.100.0",
        "iniconfig>=2.0.0",
        "kiwisolver>=1.4.5",
        "matplotlib>=3.8.0",
        "mypy>=1.10.0",
        "mypy-extensions>=1.0.0",
        "networkx>=3.2.0",
        "numpy>=2.0.0",
        "packaging>=24.0",
        "pathspec>=0.12.0",
        "Pillow>=10.0.0",
        "platformdirs>=4.0.0",
        "pluggy>=1.5.0",
        "pyparsing>=3.1.0",
        "pytest>=8.0.0",
        "pytest-cov>=5.0.0",
        "python-dateutil>=2.9.0",
        "six>=1.16.0",
        "sortedcontainers>=2.4.0",
        "soupsieve>=2.5",
        "typing_extensions>=4.10.0",
    ],
    python_requires=">=3.11",
    version=__version__,
    description="A library of music domain specific objects.",
    author="Daniel Young",
    license="MIT",
)
